const quote = document.querySelector(".quote");
const author = document.querySelector(".author");

const quotes = [
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "The way to get started is to quit talking and begin doing.",
    "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma – which is living with the results of other people's thinking.",
    "If life were predictable it would cease to be life, and be without flavor.",
    "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough.",
    "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success.",
    "Life is what happens when you're busy making other plans.",
    "Spread love everywhere you go. Let no one ever come to you without leaving happier.",
    "When you reach the end of your rope, tie a knot in it and hang on.",
    "Always remember that you are absolutely unique. Just like everyone else.",
    "Don't judge each day by the harvest you reap but by the seeds that you plant.",
    "The future belongs to those who believe in the beauty of their dreams.",
    "Tell me and I forget. Teach me and I remember. Involve me and I learn.",
    "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart.",
    "It is during our darkest moments that we must focus to see the light.",
    "Whoever is happy will make others happy too.",
    "Do not go where the path may lead, go instead where there is no path and leave a trail.",
    "You will face many defeats in life, but never let yourself be defeated.",
    "The greatest glory in living lies not in never falling, but in rising every time we fall.",
    "In the end, it's not the years in your life that count. It's the life in your years.",
    "Life is either a daring adventure or nothing at all.",
    "Many of life's failures are people who did not realize how close they were to success when they gave up.",
    "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose.",
    "An unexamined life is not worth living.",
    "Everything you've ever wanted is on the other side of fear.",
    "Life is 10% what happens to us and 90% how we react to it.",
    "Believe you can and you're halfway there.",
    "To handle yourself, use your head; to handle others, use your heart.",
    "Too many of us are not living our dreams because we are living our fears.",
    "Do what you can, with what you have, where you are.",
    "If you want to live a happy life, tie it to a goal, not to people or things.",
    "What we think, we become.",
    "Limitations live only in our minds. But if we use our imaginations, our possibilities become limitless.",
    "The best revenge is massive success.",
    "Life is short, and it is up to you to make it sweet.",
    "Life is a series of natural and spontaneous changes. Don't resist them; that only creates sorrow. Let reality be reality. Let things flow naturally forward in whatever way they like.",
    "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.",
    "You miss 100% of the shots you don't take.",
    "I have learned over the years that when one's mind is made up, this diminishes fear.",
    "I alone cannot change the world, but I can cast a stone across the water to create many ripples.",
    "Nothing is impossible, the word itself says, 'I'm possible'!",
    "The only limit to our realization of tomorrow will be our doubts of today.",
    "It is never too late to be what you might have been.",
    "You become what you believe.",
    "I would rather die of passion than of boredom.",
    "A person who never made a mistake never tried anything new.",
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",
    "Life is never fair, and perhaps it is a good thing for most of us that it is not.",
    "Only a life lived for others is a life worthwhile.",
    "Change your thoughts and you change your world.",
    "No act of kindness, no matter how small, is ever wasted.",
    "The only way to do great work is to love what you do.",
    "If you can dream it, you can achieve it.",
]

const authors = [
    "Nelson Mandela",
    "Walt Disney",
    "Steve Jobs",
    "Eleanor Roosevelt",
    "Oprah Winfrey",
    "James Cameron",
    "John Lennon",
    "Mother Teresa",
    "Franklin D. Roosevelt",
    "Margaret Mead",
    "Robert Louis Stevenson",
    "Eleanor Roosevelt",
    "Benjamin Franklin",
    "Helen Keller",
    "Aristotle",
    "Anne Frank",
    "Ralph Waldo Emerson",
    "Maya Angelou",
    "Nelson Mandela",
    "Abraham Lincoln",
    "Helen Keller",
    "Thomas Edison",
    "Dr. Seuss",
    "Socrates",
    "George Addair",
    "Charles R. Swindoll",
    "Theodore Roosevelt",
    "Eleanor Roosevelt",
    "Les Brown",
    "Theodore Roosevelt",
    "Albert Einstein",
    "Buddha",
    "Jamie Paolinetti",
    "Frank Sinatra",
    "Sarah Louise Delany",
    "Lao Tzu",
    "Buddha",
    "Wayne Gretzky",
    "Rosa Parks",
    "Mother Teresa",
    "Audrey Hepburn",
    "Franklin D. Roosevelt",
    "George Eliot",
    "Oprah Winfrey",
    "Vincent Van Gogh",
    "Albert Einstein",
    "Johann Wolfgang von Goethe",
    "Oscar Wilde",
    "Albert Einstein",
    "Norman Vincent Peale",
    "Aesop",
    "Steve Jobs",
    "Genghis Khan",
]

const randomNumber = Math.floor(Math.random() * quotes.length);

quote.innerText = quotes[randomNumber]
author.innerText = authors[randomNumber]

const continueBtn = document.querySelector(".comment__continue");
function changeQuote(event) {
    const newRandomNumber = Math.floor(Math.random() * quotes.length);
    quote.innerText = quotes[newRandomNumber]
    author.innerText = authors[newRandomNumber]
}
continueBtn.addEventListener("click", changeQuote)